#spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/testdb;MODE=MYSQL
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    show_sql: true
#    hibernate:
#      ddl-auto: update
#  database-platform: org.hibernate.dialect.MySQL8Dialect







